---
- name: ensure old versions are uninstalled
  become: true
  ansible.builtin.apt:
    state: absent    
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc

- name: ensure package dependencies
  become: true
  ansible.builtin.apt:
    state: present
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release

- name: add docker apt key
  become: true
  ansible.builtin.apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg
    state: present

- name: add docker apt repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
  register: docker_repository

- name: update package cache
  become: true
  ansible.builtin.apt:
    update_cache: yes
  when: docker_repository.changed

- name: install docker
  become: true
  ansible.builtin.apt:
    state: present
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: ensure docker is started and enabled at boot
  become: true
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: ensure docker group exists
  become: true
  ansible.builtin.group:
    name: docker
    state: present
    system: yes

- name: ensure docker users are added to the docker group
  become: true
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  register: docker_users_added
  with_items: "{{ docker_users }}"
